### ISSUE TITLE
block_devices should not be mandatory in ec2 section

### ISSUE THREAD

**Issue by milosgajdos** [ministryofjustice/bootstrap-cfn#3]
If I don't care about attached volume to an instance I'm trying to create I should not need `block_devices` section/parameter to be present in my configuration file. Some default value should be used:

Example (incomplete) config snippet:

``` yaml
dev:
  ec2:
    auto_scaling:
      desired: 1
      max: 3
      min: 0
    tags:
      Project: docker-registry
      Role: docker
      App: docker-registry
      Env: dev
    parameters:
      KeyName: default
      InstanceType: t2.medium
```

Error:

``` bash
Traceback (most recent call last):
  File "/Users/milosgajdos/projects/bootstrap-cfn/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Users/milosgajdos/projects/bootstrap-cfn/lib/python2.7/site-packages/fabric/tasks.py", line 424, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/milosgajdos/projects/bootstrap-cfn/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/milosgajdos/repos/bootstrap-cfn/fabfile.py", line 78, in cfn_create
    stack = cfn.create(stack_name, cfn_config.process())
  File "/Users/milosgajdos/repos/bootstrap-cfn/helpers/config.py", line 49, in process
    ec2 = self.ec2()
  File "/Users/milosgajdos/repos/bootstrap-cfn/helpers/config.py", line 189, in ec2
    for i in self.data['ec2']['block_devices']:
KeyError: 'block_devices'
```

Something like 10G seems reasonable enough to me.
## Acceptance
- [ ] Sane defaults provided for block_devices secton
- [ ] Tests added to cover this case
- [ ] Docs added to readme.

**Comment by ashb** [comment]
https://trello.com/c/eu9Vky5B
