### ISSUE TITLE
Handle config file not found more gracefully

### ISSUE THREAD

**Issue by ashb** [ministryofjustice/bootstrap-cfn#98]
If you run `fab config:i-dont-exist.yml` you get this behaviour:

```
Traceback (most recent call last):
  File "/Users/aberlin/.virtualenvs/cbo-deploy/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Users/aberlin/.virtualenvs/cbo-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 424, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/aberlin/.virtualenvs/cbo-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/aberlin/.virtualenvs/cbo-deploy/lib/python2.7/site-packages/bootstrap_cfn/fab_tasks.py", line 119, in cfn_delete
    cfn_config = get_config()
  File "/Users/aberlin/.virtualenvs/cbo-deploy/lib/python2.7/site-packages/bootstrap_cfn/fab_tasks.py", line 102, in get_config
    passwords=env.stack_passwords)
  File "/Users/aberlin/.virtualenvs/cbo-deploy/lib/python2.7/site-packages/bootstrap_cfn/config.py", line 16, in __init__
    self.config = self.load_yaml(config)[environment]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

This is _far_ from optimal and we should check for the file not existing instead.

**Comment by bennythejudge** [comment]
submitted PR: https://github.com/ministryofjustice/bootstrap-cfn/pull/100

**Comment by lukaszraczylo** [comment]
Submitted PR LGTM
